title: The Unknown
author: Heather
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Click the site link if you dare, it won't hurt. After all the internet isn't real, or is it?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
